"""Figure layout editor presentation for Figure Composer."""

from __future__ import annotations

import typing

from qtpy import QtCore, QtGui, QtWidgets

import erlab
from erlab.interactive._figurecomposer._defaults import _MM_PER_INCH
from erlab.interactive._figurecomposer._model._gridspec import (
    _gridspec_add_region,
    _gridspec_all_axes_ids,
    _gridspec_axis_code_names,
    _gridspec_axis_display_name,
    _gridspec_axis_variable_name_error,
    _gridspec_grid_by_id,
    _gridspec_grid_display_name,
    _gridspec_grid_display_names,
    _gridspec_grid_path,
    _gridspec_has_invalid_regions,
    _gridspec_nearest_axes_after_region_delete,
    _gridspec_region_label,
    _gridspec_region_valid,
    _gridspec_remove_region,
    _gridspec_update_axis_variable_name,
    _gridspec_update_grid_settings,
    _gridspec_update_region_span,
)
from erlab.interactive._figurecomposer._model._state import (
    FigureGridSpecGridState,
    FigureGridSpecSpanState,
    FigureSubplotsState,
)
from erlab.interactive._figurecomposer._text import (
    _format_tuple,
    _literal_sequence_from_text,
)
from erlab.interactive._figurecomposer._ui._axes_widgets import (
    _GridSpecRegionInfo,
    _GridSpecViewWidget,
)
from erlab.interactive._figurecomposer._ui._panel_controls import _step_toolbar_button
from erlab.interactive._widgets import _Separator

if typing.TYPE_CHECKING:
    from collections.abc import Iterable


class FigureLayoutPanel(QtWidgets.QWidget):
    """Edit a figure setup while leaving document commits to the owner."""

    setup_requested = QtCore.Signal(object)
    layout_mode_requested = QtCore.Signal(str)

    def __init__(self, parent: QtWidgets.QWidget | None = None) -> None:
        super().__init__(parent)
        self.setObjectName("figureComposerLayoutPage")
        self._setup = FigureSubplotsState()
        self._reserved_names: tuple[str, ...] = ()
        self._active_grid_id = self._setup.gridspec.root.grid_id
        self._pending_selected_region_id: str | None = None
        self._breadcrumb_buttons: list[QtWidgets.QToolButton] = []
        self._syncing = False
        self._released = False
        self._build_ui()
        self.set_setup(self._setup)

    def set_setup(
        self,
        setup: FigureSubplotsState,
        *,
        reserved_names: Iterable[str] = (),
        selected_region_id: str | None = None,
    ) -> None:
        """Project one immutable setup snapshot into every layout control."""
        if self._released:
            return
        previous_selection = self.gridspec_layout_widget.selected_region_id()
        desired_selection = (
            selected_region_id
            if selected_region_id is not None
            else self._pending_selected_region_id
        )
        if desired_selection is None:
            desired_selection = previous_selection
        self._pending_selected_region_id = None
        self._setup = setup
        self._reserved_names = tuple(reserved_names)
        if (
            setup.layout_mode != "gridspec"
            or _gridspec_grid_by_id(setup, self._active_grid_id) is None
        ):
            self._active_grid_id = setup.gridspec.root.grid_id

        self._syncing = True
        try:
            self._set_combo_value(self.layout_mode_combo, setup.layout_mode)
            self._sync_active_grid_controls()
            self.width_spin.setValue(setup.figsize[0])
            self.height_spin.setValue(setup.figsize[1])
            self._sync_size_mm_controls()
            self.dpi_spin.setValue(setup.dpi)
            self._set_combo_value(self.layout_combo, setup.layout or "default")
            self._set_combo_value(self.sharex_combo, str(setup.sharex))
            self._set_combo_value(self.sharey_combo, str(setup.sharey))
            self._refresh_gridspec_editor()
            self.gridspec_layout_widget.set_selected_region(desired_selection)
            self._refresh_gridspec_region_controls()
        finally:
            self._syncing = False

    def set_reserved_names(self, reserved_names: Iterable[str]) -> None:
        """Update names unavailable to generated axes variables.

        Source edits do not change the figure setup, but they can change both the
        displayed autogenerated axes names and validation of the selected axes name.
        Refresh those projections without emitting a layout edit.
        """
        names = tuple(reserved_names)
        if self._released or names == self._reserved_names:
            return
        self._reserved_names = names
        if self._setup.layout_mode == "gridspec":
            self._refresh_gridspec_editor()

    def set_validation(self, text: str, *, invalid_name: bool = False) -> None:
        """Present a rejected layout edit without changing document state."""
        self.gridspec_region_label_edit.setProperty("invalid", invalid_name)
        self.gridspec_status_label.setText(text)

    def release(self) -> None:
        """Detach application-wide event filters before owner teardown."""
        if self._released:
            return
        self._released = True
        self.gridspec_layout_widget.release()

    def closeEvent(self, event: QtGui.QCloseEvent | None) -> None:
        self.release()
        if event is not None:
            super().closeEvent(event)

    def _build_ui(self) -> None:
        layout = QtWidgets.QGridLayout(self)
        layout.setContentsMargins(6, 6, 6, 6)
        layout.setHorizontalSpacing(8)
        layout.setVerticalSpacing(6)
        layout.setColumnStretch(2, 1)
        layout.setColumnStretch(4, 1)

        self.nrows_spin = erlab.interactive.utils.BetterSpinBox(
            self, integer=True, minimum=1
        )
        self.ncols_spin = erlab.interactive.utils.BetterSpinBox(
            self, integer=True, minimum=1
        )
        self.width_spin = QtWidgets.QDoubleSpinBox(self)
        self.width_spin.setRange(0.25, 100.0)
        self.width_spin.setDecimals(3)
        self.width_spin.setSingleStep(0.25)
        self.height_spin = QtWidgets.QDoubleSpinBox(self)
        self.height_spin.setRange(0.25, 100.0)
        self.height_spin.setDecimals(3)
        self.height_spin.setSingleStep(0.25)
        self.width_mm_spin = QtWidgets.QDoubleSpinBox(self)
        self.width_mm_spin.setRange(0.25 * _MM_PER_INCH, 100.0 * _MM_PER_INCH)
        self.width_mm_spin.setDecimals(2)
        self.width_mm_spin.setSingleStep(1.0)
        self.height_mm_spin = QtWidgets.QDoubleSpinBox(self)
        self.height_mm_spin.setRange(0.25 * _MM_PER_INCH, 100.0 * _MM_PER_INCH)
        self.height_mm_spin.setDecimals(2)
        self.height_mm_spin.setSingleStep(1.0)
        self.dpi_spin = QtWidgets.QDoubleSpinBox(self)
        self.dpi_spin.setObjectName("figureComposerDpiSpin")
        self.dpi_spin.setRange(1.0, 10000.0)
        self.dpi_spin.setDecimals(1)
        self.dpi_spin.setSingleStep(10.0)
        for spinbox in (
            self.nrows_spin,
            self.ncols_spin,
            self.width_spin,
            self.height_spin,
            self.width_mm_spin,
            self.height_mm_spin,
            self.dpi_spin,
        ):
            spinbox.setKeyboardTracking(False)

        self.layout_combo = QtWidgets.QComboBox(self)
        self.layout_combo.addItems(
            ["default", "constrained", "compressed", "tight", "none"]
        )
        self.sharex_combo = QtWidgets.QComboBox(self)
        self.sharex_combo.addItems(["False", "True", "row", "col", "all"])
        self.sharey_combo = QtWidgets.QComboBox(self)
        self.sharey_combo.addItems(["False", "True", "row", "col", "all"])
        self.width_ratios_edit = QtWidgets.QLineEdit(self)
        self.width_ratios_edit.setObjectName("figureComposerWidthRatiosEdit")
        self.height_ratios_edit = QtWidgets.QLineEdit(self)
        self.height_ratios_edit.setObjectName("figureComposerHeightRatiosEdit")
        self.layout_mode_combo = QtWidgets.QComboBox(self)
        self.layout_mode_combo.setObjectName("figureComposerLayoutModeCombo")
        self.layout_mode_combo.addItems(["subplots", "gridspec"])
        self.layout_mode_combo.setToolTip(
            "Choose regular plt.subplots layout or custom GridSpec regions."
        )

        mode_label = QtWidgets.QLabel("Layout mode", self)
        mode_label.setObjectName("figureComposerLayoutModeControls")
        mode_label.setBuddy(self.layout_mode_combo)
        mode_label.setToolTip(self.layout_mode_combo.toolTip())
        mode_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        layout.addWidget(mode_label, 0, 0, 1, 2)
        layout.addWidget(self.layout_mode_combo, 0, 2, 1, 3)

        self._add_grid_pair_row(
            layout,
            1,
            "Grid",
            "figureComposerGridControls",
            "Subplot grid or active GridSpec grid.",
            "Rows",
            self.nrows_spin,
            "Number of rows in the subplot grid or active GridSpec grid.",
            "Columns",
            self.ncols_spin,
            "Number of columns in the subplot grid or active GridSpec grid.",
        )
        self._build_gridspec_editor(layout)
        self._add_grid_pair_row(
            layout,
            3,
            "Size (in)",
            "figureComposerSizeControls",
            "Figure size in inches. The plot window follows this size.",
            "Width",
            self.width_spin,
            "Figure width in inches. The plot window follows this size.",
            "Height",
            self.height_spin,
            "Figure height in inches. The plot window follows this size.",
        )
        self._add_grid_pair_row(
            layout,
            4,
            "Size (mm)",
            "figureComposerSizeMmControls",
            "Figure size in millimeters, synced with the inch controls.",
            "Width",
            self.width_mm_spin,
            "Figure width in millimeters. Converted to inches for Matplotlib.",
            "Height",
            self.height_mm_spin,
            "Figure height in millimeters. Converted to inches for Matplotlib.",
        )
        dpi_tooltip = "Figure dots per inch passed to Matplotlib and generated code."
        dpi_label = QtWidgets.QLabel("DPI", self)
        dpi_label.setObjectName("figureComposerDpiControls")
        dpi_label.setBuddy(self.dpi_spin)
        dpi_label.setToolTip(dpi_tooltip)
        dpi_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.dpi_spin.setToolTip(dpi_tooltip)
        layout.addWidget(dpi_label, 5, 0, 1, 2)
        layout.addWidget(self.dpi_spin, 5, 2, 1, 3)

        layout_row_label = QtWidgets.QLabel("Layout engine", self)
        layout_row_label.setObjectName("figureComposerLayoutControls")
        layout_row_label.setToolTip(
            "Creation-time Matplotlib layout engine.\n"
            "Default omits the layout argument.\n"
            "None passes layout='none'."
        )
        layout_row_label.setBuddy(self.layout_combo)
        layout_row_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.layout_combo.setToolTip(layout_row_label.toolTip())
        layout.addWidget(layout_row_label, 6, 0, 1, 2)
        layout.addWidget(self.layout_combo, 6, 2, 1, 3)
        self._add_grid_pair_row(
            layout,
            7,
            "Share axes",
            "figureComposerShareControls",
            "Matplotlib shared-axis settings passed to plt.subplots.",
            "x",
            self.sharex_combo,
            "Matplotlib sharex setting passed to plt.subplots.",
            "y",
            self.sharey_combo,
            "Matplotlib sharey setting passed to plt.subplots.",
        )
        self._add_grid_pair_row(
            layout,
            8,
            "Ratios",
            "figureComposerRatioControls",
            "Optional width and height ratios for subplots or active GridSpec grid.",
            "Widths",
            self.width_ratios_edit,
            "Optional width ratios, one positive number per column.",
            "Heights",
            self.height_ratios_edit,
            "Optional height ratios, one positive number per row.",
        )
        layout.setRowStretch(9, 1)
        self._connect_controls()

    def _add_grid_pair_row(
        self,
        layout: QtWidgets.QGridLayout,
        row: int,
        row_label_text: str,
        row_object_name: str,
        row_tooltip: str,
        first_label: str,
        first_widget: QtWidgets.QWidget,
        first_tooltip: str,
        second_label: str,
        second_widget: QtWidgets.QWidget,
        second_tooltip: str,
    ) -> None:
        row_label = QtWidgets.QLabel(row_label_text, self)
        row_label.setObjectName(row_object_name)
        row_label.setToolTip(row_tooltip)
        row_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        layout.addWidget(row_label, row, 0)
        for column, label_text, widget, tooltip in (
            (1, first_label, first_widget, first_tooltip),
            (3, second_label, second_widget, second_tooltip),
        ):
            label = QtWidgets.QLabel(label_text, self)
            label.setBuddy(widget)
            label.setToolTip(tooltip)
            widget.setToolTip(tooltip)
            layout.addWidget(label, row, column)
            layout.addWidget(widget, row, column + 1)

    def _build_gridspec_editor(self, layout: QtWidgets.QGridLayout) -> None:
        self.gridspec_editor_container = QtWidgets.QWidget(self)
        self.gridspec_editor_container.setObjectName(
            "figureComposerGridSpecEditorContainer"
        )
        container_layout = QtWidgets.QVBoxLayout(self.gridspec_editor_container)
        container_layout.setContentsMargins(0, 2, 0, 2)
        container_layout.setSpacing(4)
        self.gridspec_editor_top_line = _Separator(
            parent=self.gridspec_editor_container
        )
        self.gridspec_editor_top_line.setObjectName(
            "figureComposerGridSpecEditorTopLine"
        )
        container_layout.addWidget(self.gridspec_editor_top_line)

        self.gridspec_editor_widget = QtWidgets.QWidget(self.gridspec_editor_container)
        self.gridspec_editor_widget.setObjectName("figureComposerGridSpecEditor")
        editor_layout = QtWidgets.QVBoxLayout(self.gridspec_editor_widget)
        editor_layout.setContentsMargins(0, 0, 0, 0)
        editor_layout.setSpacing(4)

        self.gridspec_breadcrumb_widget = QtWidgets.QWidget(self.gridspec_editor_widget)
        self.gridspec_breadcrumb_layout = QtWidgets.QHBoxLayout(
            self.gridspec_breadcrumb_widget
        )
        self.gridspec_breadcrumb_layout.setContentsMargins(0, 0, 0, 0)
        self.gridspec_breadcrumb_layout.setSpacing(2)
        editor_layout.addWidget(self.gridspec_breadcrumb_widget)

        action_layout = QtWidgets.QHBoxLayout()
        self.gridspec_region_kind_combo = QtWidgets.QComboBox(
            self.gridspec_editor_widget
        )
        self.gridspec_region_kind_combo.setObjectName(
            "figureComposerGridSpecRegionKindCombo"
        )
        self.gridspec_region_kind_combo.addItem("Axes", "axes")
        self.gridspec_region_kind_combo.addItem("Nested Grid", "grid")
        self.gridspec_region_kind_combo.setToolTip(
            "Kind of region created by the next drag gesture."
        )
        self.gridspec_parent_grid_button = _step_toolbar_button(
            self.gridspec_editor_widget,
            "figureComposerGridSpecParentButton",
            "Parent",
            "Return to the parent GridSpec grid.",
        )
        self.gridspec_parent_grid_button.clicked.connect(self._open_parent_grid)
        draw_label = QtWidgets.QLabel("Draw", self.gridspec_editor_widget)
        draw_label.setBuddy(self.gridspec_region_kind_combo)
        action_layout.addWidget(draw_label)
        action_layout.addWidget(self.gridspec_region_kind_combo)
        action_layout.addWidget(self.gridspec_parent_grid_button)
        action_layout.addStretch(1)
        editor_layout.addLayout(action_layout)

        self.gridspec_layout_widget = _GridSpecViewWidget(
            self.gridspec_editor_widget, mode="edit"
        )
        self.gridspec_layout_widget.set_creation_kind("axes")
        self.gridspec_layout_widget.sigRegionCreated.connect(self._region_created)
        self.gridspec_layout_widget.sigRegionChanged.connect(self._region_changed)
        self.gridspec_layout_widget.sigRegionSelected.connect(self._region_selected)
        self.gridspec_layout_widget.sigNestedGridActivated.connect(self._open_grid)
        self.gridspec_region_kind_combo.currentIndexChanged.connect(
            self._region_kind_changed
        )
        editor_layout.addWidget(self.gridspec_layout_widget)

        region_layout = QtWidgets.QHBoxLayout()
        self.gridspec_region_label_edit = QtWidgets.QLineEdit(
            self.gridspec_editor_widget
        )
        self.gridspec_region_label_edit.setObjectName(
            "figureComposerGridSpecRegionLabelEdit"
        )
        self.gridspec_region_label_edit.setPlaceholderText("Autogenerated")
        self.gridspec_region_label_edit.setToolTip(
            "Optional Python variable name used in generated code.\n"
            "Leave blank to use the autogenerated name."
        )
        self.gridspec_region_label_edit.editingFinished.connect(
            self._region_label_changed
        )
        self.gridspec_open_grid_button = _step_toolbar_button(
            self.gridspec_editor_widget,
            "figureComposerGridSpecOpenButton",
            "Open",
            "Edit the selected nested grid.",
        )
        self.gridspec_open_grid_button.clicked.connect(self._open_selected_grid)
        self.gridspec_delete_region_button = _step_toolbar_button(
            self.gridspec_editor_widget,
            "figureComposerGridSpecDeleteButton",
            "Delete",
            "Delete the selected axes or nested grid region.",
        )
        self.gridspec_delete_region_button.clicked.connect(self._delete_selected_region)
        self.gridspec_region_name_label = QtWidgets.QLabel(
            "Variable name", self.gridspec_editor_widget
        )
        self.gridspec_region_name_label.setBuddy(self.gridspec_region_label_edit)
        region_layout.addWidget(self.gridspec_region_name_label)
        region_layout.addWidget(self.gridspec_region_label_edit, 1)
        region_layout.addWidget(self.gridspec_open_grid_button)
        region_layout.addWidget(self.gridspec_delete_region_button)
        editor_layout.addLayout(region_layout)

        self.gridspec_status_label = QtWidgets.QLabel(self.gridspec_editor_widget)
        self.gridspec_status_label.setObjectName("figureComposerGridSpecStatus")
        self.gridspec_status_label.setWordWrap(True)
        editor_layout.addWidget(self.gridspec_status_label)

        container_layout.addWidget(self.gridspec_editor_widget)
        self.gridspec_editor_bottom_line = _Separator(
            parent=self.gridspec_editor_container
        )
        self.gridspec_editor_bottom_line.setObjectName(
            "figureComposerGridSpecEditorBottomLine"
        )
        container_layout.addWidget(self.gridspec_editor_bottom_line)
        layout.addWidget(self.gridspec_editor_container, 2, 0, 1, 5)

    def _connect_controls(self) -> None:
        for widget in (
            self.nrows_spin,
            self.ncols_spin,
            self.width_spin,
            self.height_spin,
            self.dpi_spin,
        ):
            typing.cast("QtWidgets.QAbstractSpinBox", widget).editingFinished.connect(
                self._controls_changed
            )
        self.nrows_spin.valueChanged.connect(self._controls_changed)
        self.ncols_spin.valueChanged.connect(self._controls_changed)
        for widget in (self.width_mm_spin, self.height_mm_spin):
            typing.cast("QtWidgets.QAbstractSpinBox", widget).editingFinished.connect(
                self._millimeter_controls_changed
            )
        for widget in (self.width_ratios_edit, self.height_ratios_edit):
            widget.editingFinished.connect(self._controls_changed)
        self.layout_mode_combo.currentTextChanged.connect(self._layout_mode_changed)
        self.layout_combo.currentTextChanged.connect(self._controls_changed)
        self.sharex_combo.currentTextChanged.connect(self._controls_changed)
        self.sharey_combo.currentTextChanged.connect(self._controls_changed)

    @QtCore.Slot()
    @QtCore.Slot(int)
    @QtCore.Slot(str)
    @QtCore.Slot(object)
    def _controls_changed(self, _value: object | None = None) -> None:
        if self._syncing or self._released:
            return
        try:
            width_ratios = self._ratio_tuple(self.width_ratios_edit.text())
            height_ratios = self._ratio_tuple(self.height_ratios_edit.text())
            common_updates = {
                "figsize": (self.width_spin.value(), self.height_spin.value()),
                "dpi": self.dpi_spin.value(),
                "layout": self._layout_value(),
            }
            if self._setup.layout_mode == "gridspec":
                setup = FigureSubplotsState.model_validate(
                    {
                        **self._setup.model_dump(mode="python"),
                        **common_updates,
                    }
                )
                setup = _gridspec_update_grid_settings(
                    setup,
                    self._active_grid_id,
                    nrows=self.nrows_spin.value(),
                    ncols=self.ncols_spin.value(),
                    width_ratios=width_ratios,
                    height_ratios=height_ratios,
                )
            else:
                setup = FigureSubplotsState(
                    layout_mode="subplots",
                    nrows=self.nrows_spin.value(),
                    ncols=self.ncols_spin.value(),
                    figsize=(self.width_spin.value(), self.height_spin.value()),
                    dpi=self.dpi_spin.value(),
                    layout=self._layout_value(),
                    sharex=self._combo_bool_or_text(self.sharex_combo),
                    sharey=self._combo_bool_or_text(self.sharey_combo),
                    width_ratios=width_ratios,
                    height_ratios=height_ratios,
                    gridspec=self._setup.gridspec,
                )
        except ValueError:
            return
        if setup != self._setup:
            self.setup_requested.emit(setup)

    @QtCore.Slot()
    def _millimeter_controls_changed(self) -> None:
        if self._syncing or self._released:
            return
        self._syncing = True
        try:
            self.width_spin.setValue(self.width_mm_spin.value() / _MM_PER_INCH)
            self.height_spin.setValue(self.height_mm_spin.value() / _MM_PER_INCH)
        finally:
            self._syncing = False
        self._controls_changed()

    @QtCore.Slot(str)
    def _layout_mode_changed(self, mode: str) -> None:
        if self._syncing or self._released or mode == self._setup.layout_mode:
            return
        self.layout_mode_requested.emit(mode)

    @QtCore.Slot(int)
    def _region_kind_changed(self, _index: int) -> None:
        kind = typing.cast(
            'typing.Literal["axes", "grid"]',
            self.gridspec_region_kind_combo.currentData(),
        )
        self.gridspec_layout_widget.set_creation_kind(kind)
        grid = _gridspec_grid_by_id(self._setup, self._active_grid_id)
        if grid is not None:
            self._refresh_gridspec_status(grid)

    @QtCore.Slot(object, str)
    def _region_created(self, span_object: object, kind_text: str) -> None:
        span = typing.cast("FigureGridSpecSpanState", span_object)
        kind = typing.cast('typing.Literal["axes", "grid"]', kind_text)
        try:
            setup, region_id = _gridspec_add_region(
                self._setup, self._active_grid_id, span, kind
            )
        except ValueError as exc:
            self.set_validation(str(exc))
            return
        if region_id:
            self._request_setup(setup, selected_region_id=region_id)

    @QtCore.Slot(str, object)
    def _region_changed(self, region_id: str, span_object: object) -> None:
        span = typing.cast("FigureGridSpecSpanState", span_object)
        try:
            setup = _gridspec_update_region_span(
                self._setup, self._active_grid_id, region_id, span
            )
        except ValueError as exc:
            self.set_validation(str(exc))
            return
        self._request_setup(setup, selected_region_id=region_id)

    @QtCore.Slot(str, str)
    def _region_selected(self, region_id: str, _kind: str) -> None:
        self.gridspec_layout_widget.set_selected_region(region_id)
        self._refresh_gridspec_region_controls()

    @QtCore.Slot(str)
    def _open_grid(self, grid_id: str) -> None:
        if _gridspec_grid_by_id(self._setup, grid_id) is None:
            return
        self._active_grid_id = grid_id
        self._syncing = True
        try:
            self._sync_active_grid_controls()
        finally:
            self._syncing = False
        self._refresh_gridspec_editor()

    @QtCore.Slot()
    def _open_selected_grid(self) -> None:
        if region_id := self.gridspec_layout_widget.selected_region_id():
            self._open_grid(region_id)

    @QtCore.Slot()
    def _open_parent_grid(self) -> None:
        path = _gridspec_grid_path(self._setup, self._active_grid_id)
        if len(path) > 1:
            self._open_grid(path[-2].grid_id)

    @QtCore.Slot()
    def _delete_selected_region(self) -> None:
        region_id = self.gridspec_layout_widget.selected_region_id()
        if not region_id:
            return
        selected_region_id = _gridspec_nearest_axes_after_region_delete(
            self._setup, self._active_grid_id, region_id
        )
        setup = _gridspec_remove_region(self._setup, self._active_grid_id, region_id)
        self._request_setup(setup, selected_region_id=selected_region_id)

    @QtCore.Slot()
    def _region_label_changed(self) -> None:
        region_id = self.gridspec_layout_widget.selected_region_id()
        if not region_id:
            return
        name = self.gridspec_region_label_edit.text().strip()
        error = _gridspec_axis_variable_name_error(
            self._setup,
            region_id,
            name,
            reserved_names=self._reserved_names,
        )
        if error:
            self.set_validation(error, invalid_name=True)
            return
        self.gridspec_region_label_edit.setProperty("invalid", False)
        grid = _gridspec_grid_by_id(self._setup, self._active_grid_id)
        if grid is not None:
            self._refresh_gridspec_status(grid)
        setup = _gridspec_update_axis_variable_name(self._setup, region_id, name)
        self._request_setup(setup, selected_region_id=region_id)

    def _request_setup(
        self, setup: FigureSubplotsState, *, selected_region_id: str | None = None
    ) -> None:
        if setup == self._setup:
            return
        self._pending_selected_region_id = selected_region_id
        self.setup_requested.emit(setup)

    def _sync_active_grid_controls(self) -> None:
        setup = self._setup
        if setup.layout_mode == "gridspec":
            grid = _gridspec_grid_by_id(setup, self._active_grid_id)
            if grid is None:
                self._active_grid_id = setup.gridspec.root.grid_id
                grid = setup.gridspec.root
            self.nrows_spin.setValue(grid.nrows)
            self.ncols_spin.setValue(grid.ncols)
            self.width_ratios_edit.setText(_format_tuple(grid.width_ratios))
            self.height_ratios_edit.setText(_format_tuple(grid.height_ratios))
        else:
            self.nrows_spin.setValue(setup.nrows)
            self.ncols_spin.setValue(setup.ncols)
            self.width_ratios_edit.setText(_format_tuple(setup.width_ratios))
            self.height_ratios_edit.setText(_format_tuple(setup.height_ratios))
        gridspec_mode = setup.layout_mode == "gridspec"
        self.gridspec_editor_container.setVisible(gridspec_mode)
        self.gridspec_editor_widget.setVisible(gridspec_mode)
        self.sharex_combo.setEnabled(not gridspec_mode)
        self.sharey_combo.setEnabled(not gridspec_mode)

    def _sync_size_mm_controls(self) -> None:
        self.width_mm_spin.setValue(self._setup.figsize[0] * _MM_PER_INCH)
        self.height_mm_spin.setValue(self._setup.figsize[1] * _MM_PER_INCH)

    def _refresh_gridspec_editor(self) -> None:
        setup = self._setup
        if setup.layout_mode != "gridspec":
            self.gridspec_editor_widget.setVisible(False)
            return
        self.gridspec_editor_widget.setVisible(True)
        grid = _gridspec_grid_by_id(setup, self._active_grid_id)
        if grid is None:
            self._active_grid_id = setup.gridspec.root.grid_id
            grid = setup.gridspec.root
        grid_names = _gridspec_grid_display_names(setup)
        regions = [
            _GridSpecRegionInfo(
                axis.axes_id,
                "axes",
                axis.span,
                _gridspec_axis_display_name(
                    setup, axis.axes_id, reserved_names=self._reserved_names
                ),
                _gridspec_region_valid(grid, axis.span),
            )
            for axis in grid.axes
        ]
        regions.extend(
            _GridSpecRegionInfo(
                child.grid_id,
                "grid",
                child.span,
                grid_names.get(child.grid_id, child.grid_id),
                _gridspec_region_valid(grid, child.span),
            )
            for child in grid.child_grids
            if child.span is not None
        )
        self.gridspec_layout_widget.set_edit_grid(
            grid,
            regions,
            {
                axes_id: _gridspec_axis_display_name(
                    setup, axes_id, reserved_names=self._reserved_names
                )
                for axes_id in _gridspec_all_axes_ids(setup)
            },
        )
        self._refresh_gridspec_breadcrumbs()
        self._refresh_gridspec_region_controls()
        self._refresh_gridspec_status(grid)

    def _refresh_gridspec_status(self, grid: FigureGridSpecGridState) -> None:
        invalid_regions = [
            _gridspec_region_label(
                self._setup,
                grid,
                axis.axes_id,
                reserved_names=self._reserved_names,
            )
            for axis in grid.axes
            if not _gridspec_region_valid(grid, axis.span)
        ]
        invalid_regions.extend(
            _gridspec_region_label(
                self._setup,
                grid,
                child.grid_id,
                reserved_names=self._reserved_names,
            )
            for child in grid.child_grids
            if child.span is None or not _gridspec_region_valid(grid, child.span)
        )
        if invalid_regions:
            self.gridspec_status_label.setText(
                "Some regions are outside the active grid: "
                + ", ".join(invalid_regions)
                + ". Increase rows/columns or delete and redraw them."
            )
        elif _gridspec_has_invalid_regions(self._setup.gridspec.root):
            self.gridspec_status_label.setText(
                "A nested grid contains regions outside its bounds."
            )
        else:
            kind = self.gridspec_region_kind_combo.currentText()
            self.gridspec_status_label.setText(
                f"Drag cells to create {kind.lower()} regions. "
                "Double-click a nested grid to edit it."
            )

    def _refresh_gridspec_breadcrumbs(self) -> None:
        while self.gridspec_breadcrumb_layout.count():
            item = self.gridspec_breadcrumb_layout.takeAt(0)
            if item is None:
                continue
            if widget := item.widget():
                widget.deleteLater()
        self._breadcrumb_buttons.clear()
        path = _gridspec_grid_path(self._setup, self._active_grid_id)
        for index, grid in enumerate(path):
            if index:
                self.gridspec_breadcrumb_layout.addWidget(
                    QtWidgets.QLabel(">", self.gridspec_breadcrumb_widget)
                )
            button = QtWidgets.QToolButton(self.gridspec_breadcrumb_widget)
            button.setText(_gridspec_grid_display_name(self._setup, grid.grid_id))
            button.setToolTip("Open this GridSpec grid.")
            button.clicked.connect(
                lambda _checked=False, grid_id=grid.grid_id: self._open_grid(grid_id)
            )
            self._breadcrumb_buttons.append(button)
            self.gridspec_breadcrumb_layout.addWidget(button)
        self.gridspec_breadcrumb_layout.addStretch(1)
        self.gridspec_parent_grid_button.setEnabled(len(path) > 1)

    def _refresh_gridspec_region_controls(self) -> None:
        region_id = self.gridspec_layout_widget.selected_region_id()
        grid = _gridspec_grid_by_id(self._setup, self._active_grid_id)
        label = ""
        kind = ""
        placeholder = "Autogenerated"
        if grid is not None and region_id:
            code_names = _gridspec_axis_code_names(
                self._setup, reserved_names=self._reserved_names
            )
            for axis in grid.axes:
                if axis.axes_id == region_id:
                    label = axis.label
                    kind = "axes"
                    placeholder = (
                        f"Autogenerated: {code_names.get(region_id, region_id)}"
                    )
                    break
            if not kind and any(
                child.grid_id == region_id for child in grid.child_grids
            ):
                kind = "grid"
        with QtCore.QSignalBlocker(self.gridspec_region_label_edit):
            self.gridspec_region_label_edit.setText(label)
        has_region = bool(kind)
        self.gridspec_region_label_edit.setPlaceholderText(placeholder)
        self.gridspec_region_label_edit.setProperty("invalid", False)
        self.gridspec_region_name_label.setVisible(kind != "grid")
        self.gridspec_region_label_edit.setVisible(kind != "grid")
        self.gridspec_region_label_edit.setEnabled(kind == "axes")
        self.gridspec_delete_region_button.setEnabled(has_region)
        self.gridspec_open_grid_button.setEnabled(kind == "grid")
        self.gridspec_open_grid_button.setToolTip(
            "Edit the selected nested grid."
            if kind == "grid"
            else "Select a nested grid region to edit it."
        )
        self.gridspec_delete_region_button.setToolTip(
            "Delete the selected axes or nested grid region."
            if has_region
            else "Select an axes or nested grid region to delete it."
        )

    @staticmethod
    def _set_combo_value(combo: QtWidgets.QComboBox, value: str) -> None:
        combo.setCurrentIndex(max(combo.findText(value), 0))

    @staticmethod
    def _ratio_tuple(text: str) -> tuple[float, ...]:
        values = tuple(float(value) for value in _literal_sequence_from_text(text))
        if any(value <= 0.0 for value in values):
            raise ValueError("subplot ratios must be positive")
        return values

    def _layout_value(
        self,
    ) -> typing.Literal["constrained", "compressed", "tight", "none"] | None:
        text = self.layout_combo.currentText()
        if text == "default":
            return None
        return typing.cast(
            'typing.Literal["constrained", "compressed", "tight", "none"]',
            text,
        )

    @staticmethod
    def _combo_bool_or_text(
        combo: QtWidgets.QComboBox,
    ) -> bool | typing.Literal["none", "all", "row", "col"]:
        text = combo.currentText()
        if text == "True":
            return True
        if text == "False":
            return False
        return typing.cast('typing.Literal["none", "all", "row", "col"]', text)
