"""GridSpec layout helpers for Figure Composer."""

from __future__ import annotations

import keyword
import typing

from erlab.interactive._figurecomposer._state import (
    FigureGridSpecAxesState,
    FigureGridSpecGridState,
    FigureGridSpecLayoutState,
    FigureGridSpecSpanState,
    FigureSubplotsState,
)

if typing.TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Iterator


def _gridspec_all_axes(
    setup: FigureSubplotsState,
) -> tuple[FigureGridSpecAxesState, ...]:
    return tuple(_iter_axes(setup.gridspec.root))


def _gridspec_all_axes_ids(setup: FigureSubplotsState) -> tuple[str, ...]:
    return tuple(axis.axes_id for axis in _gridspec_all_axes(setup))


def _gridspec_valid_axes_ids(
    setup: FigureSubplotsState, axes_ids: Iterable[str]
) -> tuple[str, ...]:
    axes_by_id = _gridspec_valid_axes_by_id(setup)
    return tuple(
        dict.fromkeys(axis_id for axis_id in axes_ids if axis_id in axes_by_id)
    )


def _gridspec_invalid_axes_ids(
    setup: FigureSubplotsState, axes_ids: Iterable[str]
) -> tuple[str, ...]:
    axes_by_id = _gridspec_valid_axes_by_id(setup)
    return tuple(
        dict.fromkeys(axis_id for axis_id in axes_ids if axis_id not in axes_by_id)
    )


def _gridspec_axes_by_id(
    setup: FigureSubplotsState,
) -> dict[str, FigureGridSpecAxesState]:
    return {axis.axes_id: axis for axis in _gridspec_all_axes(setup)}


def _gridspec_valid_axes_by_id(
    setup: FigureSubplotsState,
) -> dict[str, FigureGridSpecAxesState]:
    return {
        axis.axes_id: axis
        for _grid, axis in _iter_valid_axes_with_grid(setup.gridspec.root)
    }


def _gridspec_axis_display_name(
    setup: FigureSubplotsState,
    axes_id: str,
    *,
    reserved_names: Iterable[str] = (),
) -> str:
    axes_by_id = _gridspec_axes_by_id(setup)
    axis = axes_by_id.get(axes_id)
    if axis is None:
        return "removed axis"
    return _gridspec_axis_code_names(setup, reserved_names=reserved_names).get(
        axes_id, axes_id
    )


def _gridspec_axis_display_names(
    setup: FigureSubplotsState,
    axes_ids: Iterable[str],
    *,
    reserved_names: Iterable[str] = (),
) -> tuple[str, ...]:
    return tuple(
        _gridspec_axis_display_name(setup, axes_id, reserved_names=reserved_names)
        for axes_id in axes_ids
    )


def _gridspec_grid_display_name(setup: FigureSubplotsState, grid_id: str) -> str:
    return _gridspec_grid_display_names(setup).get(grid_id, "removed grid")


def _gridspec_grid_display_names(setup: FigureSubplotsState) -> dict[str, str]:
    names = {setup.gridspec.root.grid_id: "Root"}
    for index, grid in enumerate(_iter_child_grids(setup.gridspec.root), start=1):
        names[grid.grid_id] = f"Grid {index}"
    return names


def _gridspec_axes_subplot_targets(
    setup: FigureSubplotsState, axes_ids: Iterable[str]
) -> tuple[tuple[int, int], ...]:
    root_targets = _gridspec_axes_root_targets(setup)
    return tuple(
        dict.fromkeys(
            cell for axes_id in axes_ids for cell in root_targets.get(axes_id, ())
        )
    )


def _gridspec_axis_code_names(
    setup: FigureSubplotsState, *, reserved_names: Iterable[str] = ()
) -> dict[str, str]:
    used = _gridspec_reserved_axis_code_names(setup, reserved_names=reserved_names)
    names: dict[str, str] = {}
    for index, axis in enumerate(_gridspec_all_axes(setup)):
        preferred = axis.label.strip()
        name = preferred if _axis_variable_name_is_available(preferred, used) else ""
        if not name:
            name = _unique_axis_code_name(f"ax{index}", used)
        used.add(name)
        names[axis.axes_id] = name
    return names


def _gridspec_axis_variable_name_error(
    setup: FigureSubplotsState,
    axes_id: str,
    name: str,
    *,
    reserved_names: Iterable[str] = (),
) -> str:
    name = name.strip()
    if not name:
        return ""
    if not name.isidentifier():
        return "Variable name must be a valid Python identifier."
    if keyword.iskeyword(name):
        return "Variable name cannot be a Python keyword."
    if name.startswith("_"):
        return "Variable name cannot start with an underscore."
    if name in _gridspec_reserved_axis_code_names(setup, reserved_names=reserved_names):
        return "Variable name is reserved for generated code."
    for index, axis in enumerate(_gridspec_all_axes(setup)):
        if axis.axes_id == axes_id:
            continue
        other_name = axis.label.strip()
        if other_name == name:
            return "Variable name must be unique."
        other_code_name = _axis_code_name_for_validation(
            setup,
            axes_id,
            axis,
            index,
            reserved_names=reserved_names,
        )
        if other_code_name == name:
            return "Variable name conflicts with an autogenerated name."
    return ""


def _gridspec_root_from_subplots(setup: FigureSubplotsState) -> FigureGridSpecGridState:
    axes = [
        FigureGridSpecAxesState(
            span=FigureGridSpecSpanState(
                row_start=row,
                row_stop=row + 1,
                col_start=col,
                col_stop=col + 1,
            )
        )
        for row in range(setup.nrows)
        for col in range(setup.ncols)
    ]
    return FigureGridSpecGridState(
        grid_id="root",
        label="Root",
        nrows=setup.nrows,
        ncols=setup.ncols,
        width_ratios=setup.width_ratios,
        height_ratios=setup.height_ratios,
        axes=tuple(axes),
    )


def _gridspec_setup_from_subplots(setup: FigureSubplotsState) -> FigureSubplotsState:
    root = _gridspec_root_from_subplots(setup)
    return setup.model_copy(
        update={
            "layout_mode": "gridspec",
            "gridspec": FigureGridSpecLayoutState(root=root),
        }
    )


def _subplots_setup_from_gridspec(setup: FigureSubplotsState) -> FigureSubplotsState:
    root = setup.gridspec.root
    return setup.model_copy(
        update={
            "layout_mode": "subplots",
            "nrows": root.nrows,
            "ncols": root.ncols,
            "width_ratios": root.width_ratios,
            "height_ratios": root.height_ratios,
        }
    )


def _gridspec_grid_by_id(
    setup: FigureSubplotsState, grid_id: str
) -> FigureGridSpecGridState | None:
    return _find_grid(setup.gridspec.root, grid_id)


def _gridspec_grid_path(
    setup: FigureSubplotsState, grid_id: str
) -> tuple[FigureGridSpecGridState, ...]:
    path = _find_grid_path(setup.gridspec.root, grid_id)
    if path:
        return path
    return (setup.gridspec.root,)


def _gridspec_replace_grid(
    setup: FigureSubplotsState,
    grid_id: str,
    updater: Callable[[FigureGridSpecGridState], FigureGridSpecGridState],
) -> FigureSubplotsState:
    root = _replace_grid(setup.gridspec.root, grid_id, updater)
    return setup.model_copy(
        update={"gridspec": setup.gridspec.model_copy(update={"root": root})}
    )


def _gridspec_update_grid_settings(
    setup: FigureSubplotsState,
    grid_id: str,
    *,
    nrows: int,
    ncols: int,
    width_ratios: Iterable[float] = (),
    height_ratios: Iterable[float] = (),
) -> FigureSubplotsState:
    """Return *setup* with validated dimensions for one existing grid."""
    grid = _gridspec_grid_by_id(setup, grid_id)
    if grid is None:
        return setup
    updated = FigureGridSpecGridState.model_validate(
        {
            **grid.model_dump(mode="python"),
            "nrows": nrows,
            "ncols": ncols,
            "width_ratios": tuple(width_ratios),
            "height_ratios": tuple(height_ratios),
        }
    )
    if updated == grid:
        return setup
    return _gridspec_replace_grid(setup, grid_id, lambda _grid: updated)


def _gridspec_region_overlaps(
    grid: FigureGridSpecGridState,
    span: FigureGridSpecSpanState,
    *,
    ignore_axes_id: str | None = None,
    ignore_grid_id: str | None = None,
) -> bool:
    for axis in grid.axes:
        if axis.axes_id != ignore_axes_id and _spans_overlap(axis.span, span):
            return True
    for child in grid.child_grids:
        if (
            child.grid_id != ignore_grid_id
            and child.span is not None
            and _spans_overlap(child.span, span)
        ):
            return True
    return False


def _gridspec_add_region(
    setup: FigureSubplotsState,
    grid_id: str,
    span: FigureGridSpecSpanState,
    kind: typing.Literal["axes", "grid"],
) -> tuple[FigureSubplotsState, str]:
    """Add one non-overlapping region, returning its stable identifier."""
    grid = _gridspec_grid_by_id(setup, grid_id)
    if grid is None:
        return setup, ""
    _validate_gridspec_region_edit(grid, span)
    if kind == "axes":
        region = FigureGridSpecAxesState(span=span)
        updated = grid.model_copy(update={"axes": (*grid.axes, region)})
        region_id = region.axes_id
    elif kind == "grid":
        region = FigureGridSpecGridState(span=span)
        updated = grid.model_copy(update={"child_grids": (*grid.child_grids, region)})
        region_id = region.grid_id
    else:
        raise ValueError(f"unknown GridSpec region kind {kind!r}")
    return (
        _gridspec_replace_grid(setup, grid_id, lambda _grid: updated),
        region_id,
    )


def _gridspec_update_region_span(
    setup: FigureSubplotsState,
    grid_id: str,
    region_id: str,
    span: FigureGridSpecSpanState,
) -> FigureSubplotsState:
    """Move or resize one direct child of a grid without allowing overlap."""
    grid = _gridspec_grid_by_id(setup, grid_id)
    if grid is None:
        return setup
    axis = next((axis for axis in grid.axes if axis.axes_id == region_id), None)
    child = next(
        (child for child in grid.child_grids if child.grid_id == region_id), None
    )
    if axis is None and child is None:
        return setup
    _validate_gridspec_region_edit(
        grid,
        span,
        ignore_axes_id=region_id,
        ignore_grid_id=region_id,
    )
    if (axis is not None and axis.span == span) or (
        child is not None and child.span == span
    ):
        return setup
    updated = grid.model_copy(
        update={
            "axes": tuple(
                item.model_copy(update={"span": span})
                if item.axes_id == region_id
                else item
                for item in grid.axes
            ),
            "child_grids": tuple(
                item.model_copy(update={"span": span})
                if item.grid_id == region_id
                else item
                for item in grid.child_grids
            ),
        }
    )
    return _gridspec_replace_grid(setup, grid_id, lambda _grid: updated)


def _gridspec_region_valid(
    grid: FigureGridSpecGridState, span: FigureGridSpecSpanState
) -> bool:
    return (
        0 <= span.row_start < span.row_stop <= grid.nrows
        and 0 <= span.col_start < span.col_stop <= grid.ncols
    )


def _validate_gridspec_region_edit(
    grid: FigureGridSpecGridState,
    span: FigureGridSpecSpanState,
    *,
    ignore_axes_id: str | None = None,
    ignore_grid_id: str | None = None,
) -> None:
    if not _gridspec_region_valid(grid, span):
        raise ValueError("Region is outside the active grid.")
    if _gridspec_region_overlaps(
        grid,
        span,
        ignore_axes_id=ignore_axes_id,
        ignore_grid_id=ignore_grid_id,
    ):
        raise ValueError("Regions cannot overlap.")


def _gridspec_has_invalid_regions(grid: FigureGridSpecGridState) -> bool:
    for axis in grid.axes:
        if not _gridspec_region_valid(grid, axis.span):
            return True
    for child in grid.child_grids:
        if child.span is None or not _gridspec_region_valid(grid, child.span):
            return True
        if _gridspec_has_invalid_regions(child):
            return True
    return False


def _iter_valid_axes_with_grid(
    grid: FigureGridSpecGridState,
) -> Iterator[tuple[FigureGridSpecGridState, FigureGridSpecAxesState]]:
    for axis in grid.axes:
        if _gridspec_region_valid(grid, axis.span):
            yield grid, axis
    for child in grid.child_grids:
        if child.span is not None and _gridspec_region_valid(grid, child.span):
            yield from _iter_valid_axes_with_grid(child)


def _gridspec_axes_root_targets(
    setup: FigureSubplotsState,
) -> dict[str, tuple[tuple[int, int], ...]]:
    root = setup.gridspec.root
    targets: dict[str, tuple[tuple[int, int], ...]] = {}

    def span_cells(span: FigureGridSpecSpanState) -> tuple[tuple[int, int], ...]:
        return tuple(
            (row, col)
            for row in range(span.row_start, span.row_stop)
            for col in range(span.col_start, span.col_stop)
        )

    def visit(
        grid: FigureGridSpecGridState, root_span: FigureGridSpecSpanState
    ) -> None:
        for axis in grid.axes:
            if _gridspec_region_valid(grid, axis.span):
                targets[axis.axes_id] = span_cells(
                    axis.span if grid.grid_id == root.grid_id else root_span
                )
        for child in grid.child_grids:
            if child.span is None or not _gridspec_region_valid(grid, child.span):
                continue
            visit(child, child.span if grid.grid_id == root.grid_id else root_span)

    visit(
        root,
        FigureGridSpecSpanState(
            row_start=0,
            row_stop=root.nrows,
            col_start=0,
            col_stop=root.ncols,
        ),
    )
    return targets


def _gridspec_remove_region(
    setup: FigureSubplotsState, grid_id: str, region_id: str
) -> FigureSubplotsState:
    def updater(grid: FigureGridSpecGridState) -> FigureGridSpecGridState:
        return grid.model_copy(
            update={
                "axes": tuple(axis for axis in grid.axes if axis.axes_id != region_id),
                "child_grids": tuple(
                    child for child in grid.child_grids if child.grid_id != region_id
                ),
            }
        )

    return _gridspec_replace_grid(setup, grid_id, updater)


def _gridspec_nearest_axes_after_region_delete(
    setup: FigureSubplotsState, grid_id: str, region_id: str
) -> str:
    """Return the nearest surviving axes in the edited grid, if one exists."""
    grid = _gridspec_grid_by_id(setup, grid_id)
    if grid is None:
        return ""
    deleted_span = next(
        (axis.span for axis in grid.axes if axis.axes_id == region_id), None
    )
    if deleted_span is None:
        deleted_span = next(
            (child.span for child in grid.child_grids if child.grid_id == region_id),
            None,
        )
    if deleted_span is None:
        return ""
    candidates = tuple(axis for axis in grid.axes if axis.axes_id != region_id)
    if not candidates:
        return ""

    def center(region_span: FigureGridSpecSpanState) -> tuple[float, float]:
        return (
            (region_span.row_start + region_span.row_stop - 1) / 2.0,
            (region_span.col_start + region_span.col_stop - 1) / 2.0,
        )

    deleted_center = center(deleted_span)

    def sort_key(
        axis: FigureGridSpecAxesState,
    ) -> tuple[float, int, int, int, int]:
        axis_center = center(axis.span)
        return (
            abs(axis_center[0] - deleted_center[0])
            + abs(axis_center[1] - deleted_center[1]),
            axis.span.row_start,
            axis.span.col_start,
            axis.span.row_stop,
            axis.span.col_stop,
        )

    return min(candidates, key=sort_key).axes_id


def _gridspec_update_axis_variable_name(
    setup: FigureSubplotsState, axes_id: str, name: str
) -> FigureSubplotsState:
    name = name.strip()

    def update_grid(grid: FigureGridSpecGridState) -> FigureGridSpecGridState:
        axes = tuple(
            axis.model_copy(update={"label": name}) if axis.axes_id == axes_id else axis
            for axis in grid.axes
        )
        children = tuple(update_grid(child) for child in grid.child_grids)
        return grid.model_copy(update={"axes": axes, "child_grids": children})

    root = update_grid(setup.gridspec.root)
    return setup.model_copy(
        update={"gridspec": setup.gridspec.model_copy(update={"root": root})}
    )


def _gridspec_region_label(
    setup: FigureSubplotsState,
    grid: FigureGridSpecGridState,
    region_id: str,
    *,
    reserved_names: Iterable[str] = (),
) -> str:
    code_names = _gridspec_axis_code_names(setup, reserved_names=reserved_names)
    grid_names = _gridspec_grid_display_names(setup)
    for axis in grid.axes:
        if axis.axes_id == region_id:
            return code_names.get(axis.axes_id, axis.axes_id)
    for child in grid.child_grids:
        if child.grid_id == region_id:
            return grid_names.get(child.grid_id, child.grid_id)
    return "removed region"


def _gridspec_span_code(
    span: FigureGridSpecSpanState, grid: FigureGridSpecGridState
) -> str:
    return (
        "["
        f"{_slice_code(span.row_start, span.row_stop, grid.nrows)}, "
        f"{_slice_code(span.col_start, span.col_stop, grid.ncols)}"
        "]"
    )


def _gridspec_axis_code_tuple(
    setup: FigureSubplotsState,
    axes_ids: Iterable[str],
    *,
    reserved_names: Iterable[str] = (),
) -> tuple[str, ...]:
    code_names = _gridspec_axis_code_names(setup, reserved_names=reserved_names)
    return tuple(code_names[axes_id] for axes_id in axes_ids if axes_id in code_names)


def _iter_axes(grid: FigureGridSpecGridState) -> Iterator[FigureGridSpecAxesState]:
    yield from grid.axes
    for child in grid.child_grids:
        yield from _iter_axes(child)


def _iter_child_grids(
    grid: FigureGridSpecGridState,
) -> Iterator[FigureGridSpecGridState]:
    for child in grid.child_grids:
        yield child
        yield from _iter_child_grids(child)


def _find_grid(
    grid: FigureGridSpecGridState, grid_id: str
) -> FigureGridSpecGridState | None:
    if grid.grid_id == grid_id:
        return grid
    for child in grid.child_grids:
        found = _find_grid(child, grid_id)
        if found is not None:
            return found
    return None


def _find_grid_path(
    grid: FigureGridSpecGridState, grid_id: str
) -> tuple[FigureGridSpecGridState, ...]:
    if grid.grid_id == grid_id:
        return (grid,)
    for child in grid.child_grids:
        path = _find_grid_path(child, grid_id)
        if path:
            return (grid, *path)
    return ()


def _replace_grid(
    grid: FigureGridSpecGridState,
    grid_id: str,
    updater: Callable[[FigureGridSpecGridState], FigureGridSpecGridState],
) -> FigureGridSpecGridState:
    if grid.grid_id == grid_id:
        return updater(grid)
    children = tuple(
        _replace_grid(child, grid_id, updater) for child in grid.child_grids
    )
    return grid.model_copy(update={"child_grids": children})


def _spans_overlap(
    first: FigureGridSpecSpanState, second: FigureGridSpecSpanState
) -> bool:
    return not (
        first.row_stop <= second.row_start
        or second.row_stop <= first.row_start
        or first.col_stop <= second.col_start
        or second.col_stop <= first.col_start
    )


def _axis_variable_name_is_available(name: str, used: set[str]) -> bool:
    return (
        bool(name)
        and name.isidentifier()
        and not keyword.iskeyword(name)
        and not name.startswith("_")
        and name not in used
    )


def _axis_code_name_for_validation(
    setup: FigureSubplotsState,
    edited_axes_id: str,
    target_axis: FigureGridSpecAxesState,
    target_index: int,
    *,
    reserved_names: Iterable[str],
) -> str:
    used = _gridspec_reserved_axis_code_names(setup, reserved_names=reserved_names)
    for index, axis in enumerate(_gridspec_all_axes(setup)):
        if axis.axes_id == edited_axes_id:
            continue
        preferred = axis.label.strip()
        name = preferred if _axis_variable_name_is_available(preferred, used) else ""
        if not name:
            name = _unique_axis_code_name(f"ax{index}", used)
        if axis.axes_id == target_axis.axes_id:
            return name
        used.add(name)
    return _unique_axis_code_name(f"ax{target_index}", used)


def _gridspec_reserved_axis_code_names(
    setup: FigureSubplotsState, *, reserved_names: Iterable[str] = ()
) -> set[str]:
    return {
        "eplt",
        "fig",
        "axs",
        "mcolors",
        "mtransforms",
        "np",
        "plt",
        *_gridspec_grid_code_names(setup),
        *reserved_names,
    }


def _gridspec_grid_code_names(setup: FigureSubplotsState) -> tuple[str, ...]:
    names = ["gs0"]

    def append_child_names(grid: FigureGridSpecGridState, grid_var: str) -> None:
        for child_index, child in enumerate(grid.child_grids):
            if child.span is None:
                continue
            child_var = f"{grid_var}_{child_index}"
            names.append(child_var)
            append_child_names(child, child_var)

    append_child_names(setup.gridspec.root, "gs0")
    return tuple(names)


def _unique_axis_code_name(base: str, used: set[str]) -> str:
    name = base
    suffix = 1
    while name in used:
        name = f"{base}_{suffix}"
        suffix += 1
    return name


def _slice_code(start: int, stop: int, size: int) -> str:
    if stop == start + 1:
        return str(start)
    if start == 0 and stop == size:
        return ":"
    if start == 0:
        return f":{stop}"
    return f"{start}:{stop}"
