name: Update changelog

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    if: github.repository == 'kmnhan/erlabpy'
    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Create venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install commitizen cz-changeup

      - name: Generate changelog
        run: uv run --no-project cz changelog

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update changelog"
            git push
          else
            echo "nothing to commit, working tree clean"
          fi
